prefix np: <http://www.nanopub.org/nschema#>
prefix prov: <http://www.w3.org/ns/prov#>

select ?nanopub ?process ?agent ?codebase where {
  graph ?headGraph {
    ?nanopub a np:Nanopublication .
    ?nanopub np:hasPublicationInfo ?publicationInfoGraph .
  }
  graph ?publicationInfoGraph {
    {
      ?nanopub prov:wasGeneratedBy ?process .
      ?process prov:wasAssociatedWith ?agent .
      ?agent prov:specializationOf ?codebase .
    } union {
      ?nanopub prov:wasAttributedTo ?agent .
    }
  }
}
