prefix np: <http://www.nanopub.org/nschema#>
prefix prov: <http://www.w3.org/ns/prov#>
prefix dct: <http://purl.org/dc/terms/>

select ?nanopub ?process ?version ?agent ?codebase {
  graph ?headGraph {
    ?nanopub a np:Nanopublication .
    ?nanopub np:hasPublicationInfo ?publicationInfoGraph .
  }
  graph ?publicationInfoGraph {
    {
      ?nanopub prov:wasGeneratedBy ?process .
      ?process prov:wasAssociatedWith ?agent .
      ?agent prov:specializationOf ?codebase .
      optional {
        ?process prov:used ?version .
        ?version dct:isVersionOf ?codebase .
      }
    } union {
      ?nanopub prov:wasAttributedTo ?agent .
    }
  }
}
